- name: "Update package"
  become: yes
  apt: 
    update_cache: yes

- name: "Upgrade package"
  become: yes
  apt:
    upgrade: yes

- name: "Copy nodejs file"
  become: yes
  copy:
    src: ../files/*
    dest: /tmp/

- name: "Install docker"
  shell: |
	sudo apt-get install docker-ce docker-ce-cli containerd.io

- name: "build docker"
  shell: |
    sudo docker build . --tag udacitycap

- name: "Run docker"
  shell: |
    sudo docker run  -p 3000:3000 udacitycap
